# Generated by Django 2.2.16 on 2021-03-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_unifiedjob_ansible_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMetrics',
            fields=[
                ('hostname', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('last_automation', models.DateTimeField()),
            ],
        ),
    ]
