# Generated by Django 2.2.16 on 2021-04-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_schedule_sort_fallback_to_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMetric',
            fields=[
                ('hostname', models.CharField(max_length=512, primary_key=True, serialize=False)),
                (
                    'first_automation',
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text='DateTime ( with timestamp ) , when the object was first created'),
                ),
                ('last_automation', models.DateTimeField(db_index=True, help_text='DateTime ( with timestamp ) , when the object was last modified')),
            ],
        ),
    ]
