# Generated by Django 2.2.16 on 2021-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_hostmetrics_first_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmetrics',
            name='first_automation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
