# Generated by Django 2.2.16 on 2021-03-30 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_auto_20210330_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmetrics',
            name='first_automation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 30, 5, 40, 44, 846312, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
